---
# tasks file for Ansible-Docker-Jenkins
- name: Add Jenkins NGINX Server Block
  template:
    src: "templates/etc/nginx/sites-available/jenkins.conf.j2"
    dest: "/etc/nginx/sites-available/jenkins.conf"
  when: ansible_os_family == 'Debian'
  tags:
    - "install"
    - "configure"

- name: Enable Jenkins NGINX Server Block
  file:
    src: "/etc/nginx/sites-available/jenkins.conf"
    dest: "/etc/nginx/sites-enabled/jenkins.conf"
    state: link
  when: ansible_os_family == 'Debian'
  notify: Restart NGINX
  tags:
    - "install"
    - "configure"
